# Application name
spring.application.name=cw-enquiry-controller

# Server settings
server.port=8085
server.servlet.context-path=/cw-enquiry-controller

# Oracle DB connection
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/ORCLPDB
spring.datasource.username=TRINITY
spring.datasource.password=Tyghvb135
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

## JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Jackson date format (optional)
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=Asia/Kolkata

# Logging
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
